#!/bin/sh

if [ $# -ne 1 ]; then
	echo "Usage: upload-apk <path-to-apk>"
	exit 1
fi

if [ ! -f $1 ]; then
	echo "File does not exist"
	exit 1
fi

read -s -p "Password: " PASSWORD

curl \
	-v \
	--anyauth \
	-u "rubycell:$PASSWORD" \
	http://rubycell.com/download/upload.php \
	--next http://rubycell.com/download/uploadAndroid.php \
	--progress-bar \
	-u "rubycell:$PASSWORD" \
	-F uploaded=@$1 > tee /dev/null
