-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:7f32b4755defd93f16707a1835419670$
-- 

return {
	texture = 'game.png',
	frames = {
			{
				name = "gemBlue.png",
				spriteColorRect = { x = 18, y = 23, width = 34, height = 24 },
				uvRect = { u0 = 0.0625, v0 = 0.03125, u1 = 0.8125, v1 = 0.5625 },
				spriteSourceSize = { width = 70, height = 70 },
				spriteTrimmed = true,
				textureRotated = true
			},
		}
	}

